from pico2d import *
import game_framework
from Cookie import *
from Background import *
from Grass import *
from barrier import *
from collide import *
from ui import *
from jelly import *
import json
import title_state
import result_state

name="MainState"
main_bgm=None
MAP_SIZE=11000
OBSTACLE,JELLY=0,1
obstacle_list=None
gameEnd=False

def create_world():
    global cookie,background,grass,obstacle,jump,jump_time,isjump,main_bgm,ui
    background=Background(800,600)
    cookie=Player()
    ui=UI()
    grass=Grass(800,60)
    #obstacle=Barrier()
    jump = False
    jump_time = 0
    isjump = 0
    main_bgm=load_music('스테이지1.wav')
    main_bgm.set_volume(32)
    main_bgm.repeat_play()
    load_map_data()

def destroy_world():
    global cookie, background, grass, obstacle,obstacle_list,ui,main_bgm
    del(cookie)
    del(background)
    del(grass)
    del(ui)
    del(main_bgm)
    #del(obstacle)
    for i in obstacle_list:
        for j in obstacle_list[i]:
            obstacle_list[i].remove(j)

def enter():
    global jump,jump_time,isjump,collision
    jump = False
    jump_time = 0
    isjump = 0
    collision=False
    create_world()

def exit():
    destroy_world()

def pause():
    pass

def resume():
    pass

def handle_events():
    events=get_events()
    for event in events:
        if (event.type,event.key)==(SDL_KEYDOWN,SDLK_ESCAPE):
            game_framework.quit()
        else:
            cookie.handle_event(event)

def update(frame_time):
    global jump, jump_time, isjump,obstacle_list,gameEnd

    if cookie.dead==True:
        game_framework.change_state(result_state)
        return

    background.update(frame_time)
    cookie.update(frame_time)
    grass.update(frame_time)
    for i in obstacle_list:
        for j in obstacle_list[i]:
            j.update(frame_time)

    for i in obstacle_list:
        for j in obstacle_list[i]:
            if i==0:
                if(collide(cookie,j)):
                    if cookie.big is False:
                        cookie.check_collision()
                        cookie.life-=10.0
                    obstacle_list[i].remove(j)
            elif i==1:
                if(collide(cookie,j)):
                    if j.type==0:
                        cookie.big=True
                        obstacle_list[i].remove(j)
                    elif j.type==1:
                        cookie.jellyCount+=j.skill
                        obstacle_list[i].remove(j)
                    elif j.type==2:
                        cookie.life+=j.skill
                        obstacle_list[i].remove(j)
                        if cookie.life>500:
                            cookie.life=500
                    elif j.type==3:
                        cookie.jellyCount+=j.skill
                        obstacle_list[i].remove(j)




def draw(frame_time):
    global collision,obstacle_list
    clear_canvas()
    background.draw()
    grass.draw()
    for i in obstacle_list:
        for j in obstacle_list[i]:
            j.draw()

    #for i in obstacle_list:
    #    for j in obstacle_list[i]:
    #        j.draw_bb()

    ui.draw()
    cookie.draw()
    #cookie.draw_bb()
    cookie.collision = False
    update_canvas()

def clear_map_data():
    global obstacle_list
    for i in obstacle_list:
        for j in obstacle_list[i]:
            obstacle_list[i].remove(j)

def load_map_data():
    #clear_map_data()
    global obstacle_list
    tempobstacle=Barrier(1000,1,0)
    tempobstacle.enter()
    obstacle_list={OBSTACLE:[tempobstacle],JELLY:[]}

    tempobstacle=Barrier(1400,1,0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(1800, 1, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(2100, 0, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)

    tempobstacle = Barrier(2300, 0, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(2700, 1, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(3000, 1, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(3300, 1, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)

    tempobstacle = Barrier(3600, 0, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(3800, 0, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(4000, 1, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(4200, 0, 0)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)

    tempobstacle = Barrier(4400, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(4700, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5000, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5150, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5300, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5500, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5600, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5750, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(5900, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6050, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6050, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6200, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6400, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6500, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6600, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(6750, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7000, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7150, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7350, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7500, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7700, 0, 1)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(7850, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)
    tempobstacle = Barrier(8000, 1, 2)
    tempobstacle.enter()
    obstacle_list[OBSTACLE].append(tempobstacle)


    tempjelly=Jelly(1000,130,1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly=Jelly(1050,100,1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1100, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1150, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1200, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1250, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1300, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1350, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1400, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1450, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1500, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1550, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1600, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1650, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1700, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1750, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1800, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1850, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1900, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(1950, 200, 0)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)

    tempjelly = Jelly(2000, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2050, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2100, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2150, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2200, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2250, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2300, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2350, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2400, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2450, 200, 2)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2500, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2550, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2600, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2650, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2700, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2750, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2800, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2850, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2900, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(2950, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)

    tempjelly = Jelly(3000, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3050, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3100, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3150, 200, 3)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3200, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3250, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3300, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3350, 200, 2)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3400, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3450, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3500, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3550, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3600, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3650, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3700, 180, 0)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3750, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3800, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3850, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3900, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(3950, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)

    tempjelly = Jelly(4000, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4050, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4100, 180, 2)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4150, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4200, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4250, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4300, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4350, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4400, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4450, 180, 3)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4500, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4550, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4600, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4650, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4700, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4750, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4800, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4850, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4900, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(4950, 170, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5000, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5050, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5150, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5200, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5250, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5300, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5350, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5400, 180, 3)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5450, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5500, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5550, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5600, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5650, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5700, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5750, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5800, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5850, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5900, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(5950, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6000, 150, 3)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6050, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6100, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6150, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6200, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6250, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6300, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6350, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6400, 170, 2)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6450, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6500, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6550, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6600, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6650, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6700, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6750, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6800, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6850, 180, 3)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6900, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(6950, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7000, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7050, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7100, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7150, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7200, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7250, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7300, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7350, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7400, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7450, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7500, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7550, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7600, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7650, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7700, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7750, 70, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7800, 100, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7850, 130, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7900, 150, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(7950, 150, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)
    obstacle_list[JELLY].append(tempjelly)
    tempjelly = Jelly(8000, 150, 1)
    tempjelly.enter()
    obstacle_list[JELLY].append(tempjelly)